name: Build and Deploy Svelte Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: |
          curl -L https://get.pnpm.io/install.js | node -
          echo 'export PATH=$HOME/.pnpm/bin:$PATH' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Copy dist folder to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          git checkout main dist
          mv dist/* .
          git add .
          git commit -m "Deploy to gh-pages"
          git push origin gh-pages --force
